name: audioplayer_speed
description: A flutter plugin to play multiple audio files simultaneously and controll speed.
version: 0.7.8
author: he <roughwin@gmail.com>
homepage: https://github.com/luanpotter/audioplayer

flutter:
  plugin:
    androidPackage: xyz.luan.audioplayers
    pluginClass: AudioplayersPlugin

dependencies:
  uuid: ^1.0.3
  path_provider: ^0.4.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.11.3+17
  test: ^1.3.0

environment:
  sdk: ">=2.0.0-dev.50.0 <3.0.0"
